### ISSUE TITLE
Issues setting message attributes on SQS batch send message requests

### ISSUE THREAD

**Issue by asylvest** [awslabs/aws-sdk-cpp#39]
Setting the message body and attributes on a `SendMessageRequest` works as expected for me.  When I try to send a `SendMessageBatchRequest`, setting the message body and string attributes on each message, the message body makes it through as expected but no attributes do.  I've tried doing this two different ways (there are a few lines of code specific to my repo mixed in here but I think this should be pretty legible... if you can't recreate this and want a self-contained application, I can put one together):

```
void SQSClient::sendMessageBatch(
        const std::vector<std::string>& messageBody,
        const std::vector<std::map<std::string, std::string>>& attributes)
{
    if (messageBody.size() != attributes.size())
    {
        throw except::Exception(Ctxt("Sizes don't match"));
    }

    SendMessageBatchRequest request;

    std::vector<SendMessageBatchRequestEntry> entries(messageBody.size());
    for (size_t ii = 0; ii < messageBody.size(); ++ii)
    {
        SendMessageBatchRequestEntry entry;
        entry.SetMessageBody(messageBody[ii].c_str());

        const std::string id("some-batch-id-" + str::toString(ii));

        entry.SetId(id.c_str());

        // Try #1
        Aws::Map<Aws::String, MessageAttributeValue> attMap;
        for (auto iter : attributes[ii])
        {
            MessageAttributeValue stringAttributeValue;
            stringAttributeValue.SetStringValue(iter.second.c_str());
            stringAttributeValue.SetDataType("String");

            attMap[iter.first.c_str()] = stringAttributeValue;
        }
        entry.SetMessageAttributes(attMap);

        // Try #2
        for (auto iter : attributes[ii])
        {
            MessageAttributeValue stringAttributeValue;
            stringAttributeValue.SetStringValue(iter.second.c_str());
            stringAttributeValue.SetDataType("String");
            entry.AddMessageAttributes(iter.first.c_str(), stringAttributeValue);
        }

        request.AddEntries(entry);
    }

    request.SetQueueUrl(mQueueUrl);

    // This succeeds, and the message bodies make it through, but no attributes do
    SendMessageBatchOutcome outcome = mSqsClient->SendMessageBatch(request);
}
```

If I'm just doing something dumb, please let me know. :o)

**Comment by prestomation** [comment]
Hi asylvest, there does seem to be a bug here. I don't think you're doing anything wrong. 
We will prioritize this bug appropriately and keep you updated

**Comment by JonathanHenson** [comment]
can you give this another try? We made some updates to query protocol and it should be fixed.

**Comment by JonathanHenson** [comment]
closing pending comments from requestor.

**Comment by asylvest** [comment]
I just tried this from a fresh clone and build of the SDK.  Unfortunately, I still get the same behavior as before with either of the two approaches above.

**Comment by asylvest** [comment]
Since the issue was not resolved, can you re-open the issue so it doesn't get lost?  Let me know when it's potentially resolved and I will try again.  Thanks.
